import { Router } from 'express';

import { authRouter } from './auth';
import { invoicesRouter } from './invoices';
import { propertiesRouter } from './properties';
import { summaryRouter } from './summary';
import { expensesRouter } from './expenses';
import { revenuesRouter } from './revenues';
import { companiesRouter } from './companies';
import { rolesRouter } from './roles';
import { userRolesRouter } from './userRoles';
import { usersRouter } from './users';
import { reportsRouter } from './reports';
import { dividendsRouter } from './dividends';
import { taxRouter } from './tax';
import { advisorsRouter } from './advisors';
import { leveragedBuybackRouter } from './leveragedBuyback';
import { valuationRouter } from './valuation';
import { personalIncomesRouter } from './personalIncomes';
import { wealthRouter } from './wealth';
import { freezeRouter } from './freeze';
import { profileRouter } from './profile';
import { personalExpensesRouter } from './personalExpenses';
import { investmentsRouter } from './investments';
import { financialGoalsRouter } from './financialGoals';
import { personalAssetsRouter } from './personalAssets';
import { personalLiabilitiesRouter } from './personalLiabilities';
import { metricsRouter } from './metrics';
import { leverageRouter } from './leverage';
import { aiRouter } from './ai';
import { monitoringRouter } from './monitoring';
import { documentsRouter } from './documents';
import { mdcRouter } from './mdc';
import { eventsRouter } from './events';
import { whyRouter } from './why';
import { graphRouter } from './graph';

const routes = Router();

routes.use('/auth', authRouter);
routes.use('/properties', propertiesRouter);
routes.use('/invoices', invoicesRouter);
routes.use('/expenses', expensesRouter);
routes.use('/revenues', revenuesRouter);
routes.use('/summary', summaryRouter);
routes.use('/companies', companiesRouter);
routes.use('/roles', rolesRouter);
routes.use('/userRoles', userRolesRouter);
routes.use('/users', usersRouter);
routes.use('/reports', reportsRouter);
routes.use('/corporate', dividendsRouter);
routes.use('/tax', taxRouter);
routes.use('/advisors', advisorsRouter);
routes.use('/leveraged-buyback', leveragedBuybackRouter);
routes.use('/valuation', valuationRouter);
routes.use('/personal-incomes', personalIncomesRouter);
routes.use('/personal-assets', personalAssetsRouter);
routes.use('/personal-liabilities', personalLiabilitiesRouter);
routes.use('/personal-expenses', personalExpensesRouter);
routes.use('/wealth', wealthRouter);
routes.use('/freeze', freezeRouter);
routes.use('/investments', investmentsRouter);
routes.use('/financial-goals', financialGoalsRouter);
routes.use('/profile', profileRouter);
routes.use('/metrics', metricsRouter);
routes.use('/leverage', leverageRouter);
routes.use('/ai', aiRouter);
routes.use('/monitoring', monitoringRouter);
routes.use('/documents', documentsRouter);
routes.use('/mdc', mdcRouter);
routes.use('/events', eventsRouter);
routes.use('/why', whyRouter);
routes.use('/graph', graphRouter);

export { routes };
